/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.mingchoi.design.pattern.practice;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
